# **DATA PREPROCESSING**

In [124]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [125]:
data = pd.read_csv('adult.csv', na_values=['#NAME ?'])
data.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [126]:
data.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
income            object
dtype: object

In [127]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [128]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()

# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
data = data.apply(le.fit_transform)

data.head()

age  workclass  fnlwgt  education  education-num  marital-status  \
0   22          7    2671          9             12               4   
1   33          6    2926          9             12               2   
2   21          4   14086         11              8               0   
3   36          4   15336          1              6               2   
4   11          4   19355          9             12               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           1             1     4    1            25             0   
1           4             0     4    1             0             0   
2           6             1     4    1             0             0   
3           6             0     2    1             0             0   
4          10             5     2    0             0             0   

   hours-per-week  native-country  income  
0              39              39       0  
1              12              39       0  
2              39              39       0  
3              39              39       0  
4              39               5       0

In [129]:
#get to view our our diagnosis column values are distributed
data['income'].value_counts()

0    24720
1     7841
Name: income, dtype: int64

## Prepare train and test dataset

In [130]:
#creating our X feature variables and y outcome variable
#X = data.drop('diagnosis',axis=1)
X = data.drop('income',axis=1)
y = data['income']

In [131]:
#splitting our data into training and testing data set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

# **Random Forest Classification**

### train_array(X_train) = train dataset WITHOUT occupancy

### test_array(X_test) = test dataset WITHOUT occupancy
### occlabel_array(y_train) = 'Occupancy' label from train dataset

In [132]:
#Random Forest Classification
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(X_train,y_train)


RandomForestClassifier()

In [133]:
#To predict occupancy using the test's set features
clf_pred=clf.predict(X_test)
print(clf_pred)

[0 0 0 ... 1 0 0]


In [134]:
# Transfer the array of predicted popularity of test data into dataframe
clf_pred_df = pd.DataFrame(data=clf_pred, columns=['income'])
clf_pred_df.head(10)

income
0       0
1       0
2       0
3       0
4       0
5       1
6       1
7       0
8       1
9       0

In [135]:
RFprob_each = clf.predict_proba(X_test)
RFprob_each

array([[0.96, 0.04],
       [0.98, 0.02],
       [0.63, 0.37],
       ...,
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.97, 0.03]])

In [136]:
pos_prob = []
for inner in RFprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.04, 0.02, 0.37, 0.23, 0.26, 0.79, 0.76, 0.21, 0.95, 0.05]

In [137]:
X_test

age  workclass  fnlwgt  education  education-num  marital-status  \
16054   25          7    8550         11              8               4   
32382   27          2    7772         11              8               0   
10749   22          2   16513          9             12               2   
15377   22          4    7565         11              8               2   
29660   12          1    4376         15              9               4   
...    ...        ...     ...        ...            ...             ...   
29785   11          4   14911         11              8               4   
8912    40          4    9800          9             12               2   
12599   32          4   10171          9             12               2   
20781    9          4   13925         15              9               4   
14472   17          6     512         11              8               4   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
16054          11             1     4    1             0             0   
32382           1             4     4    0             0             0   
10749           3             0     4    1             0             0   
15377           3             0     4    1             0             0   
29660          10             1     4    0             0            15   
...           ...           ...   ...  ...           ...           ...   
29785          14             1     4    0             0             0   
8912           12             0     4    1             0            47   
12599           1             0     4    1            79             0   
20781           8             1     4    1             0             0   
14472           5             1     4    1             0             0   

       hours-per-week  native-country  
16054              39              39  
32382              39              39  
10749              39              39  
15377              39              39  
29660              39              39  
...               ...             ...  
29785              39              39  
8912               39              39  
12599              39              39  
20781              19              39  
14472              39              39  

[6513 rows x 14 columns]

In [138]:
X_testdf = X_test.copy()
X_testdf.insert(len(X_testdf.columns),'y_test income',y_test)
X_testdf=X_testdf.reset_index(drop=True)
X_testdf

age  workclass  fnlwgt  education  education-num  marital-status  \
0      25          7    8550         11              8               4   
1      27          2    7772         11              8               0   
2      22          2   16513          9             12               2   
3      22          4    7565         11              8               2   
4      12          1    4376         15              9               4   
...   ...        ...     ...        ...            ...             ...   
6508   11          4   14911         11              8               4   
6509   40          4    9800          9             12               2   
6510   32          4   10171          9             12               2   
6511    9          4   13925         15              9               4   
6512   17          6     512         11              8               4   

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0             11             1     4    1             0             0   
1              1             4     4    0             0             0   
2              3             0     4    1             0             0   
3              3             0     4    1             0             0   
4             10             1     4    0             0            15   
...          ...           ...   ...  ...           ...           ...   
6508          14             1     4    0             0             0   
6509          12             0     4    1             0            47   
6510           1             0     4    1            79             0   
6511           8             1     4    1             0             0   
6512           5             1     4    1             0             0   

      hours-per-week  native-country  y_test income  
0                 39              39              1  
1                 39              39              0  
2                 39              39              0  
3                 39              39              0  
4                 39              39              0  
...              ...             ...            ...  
6508              39              39              0  
6509              39              39              1  
6510              39              39              1  
6511              19              39              0  
6512              39              39              0  

[6513 rows x 15 columns]

In [139]:
# Insert result into test_wtpopl, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'RForest', clf_pred_df['income'])
X_testdf

age  workclass  fnlwgt  education  education-num  marital-status  \
0      25          7    8550         11              8               4   
1      27          2    7772         11              8               0   
2      22          2   16513          9             12               2   
3      22          4    7565         11              8               2   
4      12          1    4376         15              9               4   
...   ...        ...     ...        ...            ...             ...   
6508   11          4   14911         11              8               4   
6509   40          4    9800          9             12               2   
6510   32          4   10171          9             12               2   
6511    9          4   13925         15              9               4   
6512   17          6     512         11              8               4   

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0             11             1     4    1             0             0   
1              1             4     4    0             0             0   
2              3             0     4    1             0             0   
3              3             0     4    1             0             0   
4             10             1     4    0             0            15   
...          ...           ...   ...  ...           ...           ...   
6508          14             1     4    0             0             0   
6509          12             0     4    1             0            47   
6510           1             0     4    1            79             0   
6511           8             1     4    1             0             0   
6512           5             1     4    1             0             0   

      hours-per-week  native-country  y_test income  RForest  
0                 39              39              1        0  
1                 39              39              0        0  
2                 39              39              0        0  
3                 39              39              0        0  
4                 39              39              0        0  
...              ...             ...            ...      ...  
6508              39              39              0        0  
6509              39              39              1        1  
6510              39              39              1        1  
6511              19              39              0        0  
6512              39              39              0        0  

[6513 rows x 16 columns]

# **Naive Bayes**

In [140]:
from sklearn.naive_bayes import GaussianNB

gaus = GaussianNB()
gaus.fit(X_train, y_train)

GaussianNB()

In [141]:
# To predict popularity using test set's features
NB_pred= gaus.predict(X_test)
print(NB_pred)

[0 0 0 ... 1 0 0]


In [142]:
# Transfer the array of predicted popularity of test data into dataframe
NB_pred_df = pd.DataFrame(data=NB_pred, columns=['income'])
NB_pred_df.head(10)

income
0       0
1       0
2       0
3       0
4       0
5       1
6       1
7       0
8       1
9       0

In [143]:
NBprob_each = gaus.predict_proba(X_test)
NBprob_each

array([[9.72407173e-01, 2.75928270e-02],
       [9.98151893e-01, 1.84810712e-03],
       [6.64453392e-01, 3.35546608e-01],
       ...,
       [7.95468372e-11, 1.00000000e+00],
       [9.98557269e-01, 1.44273142e-03],
       [9.86960260e-01, 1.30397396e-02]])

In [144]:
pos_prob = []
for inner in NBprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.02759282696294157,
 0.0018481071195250007,
 0.33554660773208467,
 0.16981779575093398,
 0.0060403464200278695,
 0.6337930239550678,
 0.5446200337743471,
 0.14960064202305157,
 0.9999999911702702,
 0.004498580738209833]

In [145]:
# Insert result into test_wtpopl, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'NBGaus', NB_pred_df['income'])
X_testdf

age  workclass  fnlwgt  education  education-num  marital-status  \
0      25          7    8550         11              8               4   
1      27          2    7772         11              8               0   
2      22          2   16513          9             12               2   
3      22          4    7565         11              8               2   
4      12          1    4376         15              9               4   
...   ...        ...     ...        ...            ...             ...   
6508   11          4   14911         11              8               4   
6509   40          4    9800          9             12               2   
6510   32          4   10171          9             12               2   
6511    9          4   13925         15              9               4   
6512   17          6     512         11              8               4   

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0             11             1     4    1             0             0   
1              1             4     4    0             0             0   
2              3             0     4    1             0             0   
3              3             0     4    1             0             0   
4             10             1     4    0             0            15   
...          ...           ...   ...  ...           ...           ...   
6508          14             1     4    0             0             0   
6509          12             0     4    1             0            47   
6510           1             0     4    1            79             0   
6511           8             1     4    1             0             0   
6512           5             1     4    1             0             0   

      hours-per-week  native-country  y_test income  RForest  NBGaus  
0                 39              39              1        0       0  
1                 39              39              0        0       0  
2                 39              39              0        0       0  
3                 39              39              0        0       0  
4                 39              39              0        0       0  
...              ...             ...            ...      ...     ...  
6508              39              39              0        0       0  
6509              39              39              1        1       1  
6510              39              39              1        1       1  
6511              19              39              0        0       0  
6512              39              39              0        0       0  

[6513 rows x 17 columns]

# **KNN Classification**

In [146]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [147]:
# To predict popularity using test set's features
KNN_pred= knn.predict(X_test)
print(KNN_pred)

[0 0 0 ... 1 0 0]


In [148]:
# Transfer the array of predicted popularity of test data into dataframe
KNpredct_df = pd.DataFrame(data=KNN_pred, columns=['income'])
KNpredct_df.head(10)

income
0       0
1       0
2       0
3       0
4       0
5       1
6       1
7       0
8       1
9       0

In [149]:
KNprob_each = knn.predict_proba(X_test)
KNprob_each

array([[0.57142857, 0.42857143],
       [1.        , 0.        ],
       [1.        , 0.        ],
       ...,
       [0.28571429, 0.71428571],
       [0.85714286, 0.14285714],
       [0.71428571, 0.28571429]])

In [150]:
pos_prob = []
for inner in KNprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]

[0.42857142857142855,
 0.0,
 0.0,
 0.0,
 0.14285714285714285,
 0.7142857142857143,
 0.7142857142857143,
 0.14285714285714285,
 0.7142857142857143,
 0.42857142857142855]

In [151]:
# Insert result into test_wtpopl, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'KNeigh', KNpredct_df['income'])
X_testdf


age  workclass  fnlwgt  education  education-num  marital-status  \
0      25          7    8550         11              8               4   
1      27          2    7772         11              8               0   
2      22          2   16513          9             12               2   
3      22          4    7565         11              8               2   
4      12          1    4376         15              9               4   
...   ...        ...     ...        ...            ...             ...   
6508   11          4   14911         11              8               4   
6509   40          4    9800          9             12               2   
6510   32          4   10171          9             12               2   
6511    9          4   13925         15              9               4   
6512   17          6     512         11              8               4   

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0             11             1     4    1             0             0   
1              1             4     4    0             0             0   
2              3             0     4    1             0             0   
3              3             0     4    1             0             0   
4             10             1     4    0             0            15   
...          ...           ...   ...  ...           ...           ...   
6508          14             1     4    0             0             0   
6509          12             0     4    1             0            47   
6510           1             0     4    1            79             0   
6511           8             1     4    1             0             0   
6512           5             1     4    1             0             0   

      hours-per-week  native-country  y_test income  RForest  NBGaus  KNeigh  
0                 39              39              1        0       0       0  
1                 39              39              0        0       0       0  
2                 39              39              0        0       0       0  
3                 39              39              0        0       0       0  
4                 39              39              0        0       0       0  
...              ...             ...            ...      ...     ...     ...  
6508              39              39              0        0       0       0  
6509              39              39              1        1       1       0  
6510              39              39              1        1       1       1  
6511              19              39              0        0       0       0  
6512              39              39              0        0       0       0  

[6513 rows x 18 columns]

# **Decision Tree**

In [152]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [153]:
#To predict occupancy using the test's set features
model_pred=model.predict(X_test)
print(model_pred)

[0 0 0 ... 1 0 0]


In [154]:
# Transfer the array of predicted popularity of test data into dataframe
model_pred_df = pd.DataFrame(data=model_pred, columns=['income'])
model_pred_df.head(10)

income
0       0
1       0
2       0
3       0
4       0
5       1
6       1
7       0
8       1
9       0

In [155]:
DTprob_each = model.predict_proba(X_test)
DTprob_each

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [156]:
pos_prob = []
for inner in DTprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0]

In [157]:
# Insert result into test_wtpopl, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'DecisionT', clf_pred_df['income'])
X_testdf


age  workclass  fnlwgt  education  education-num  marital-status  \
0      25          7    8550         11              8               4   
1      27          2    7772         11              8               0   
2      22          2   16513          9             12               2   
3      22          4    7565         11              8               2   
4      12          1    4376         15              9               4   
...   ...        ...     ...        ...            ...             ...   
6508   11          4   14911         11              8               4   
6509   40          4    9800          9             12               2   
6510   32          4   10171          9             12               2   
6511    9          4   13925         15              9               4   
6512   17          6     512         11              8               4   

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0             11             1     4    1             0             0   
1              1             4     4    0             0             0   
2              3             0     4    1             0             0   
3              3             0     4    1             0             0   
4             10             1     4    0             0            15   
...          ...           ...   ...  ...           ...           ...   
6508          14             1     4    0             0             0   
6509          12             0     4    1             0            47   
6510           1             0     4    1            79             0   
6511           8             1     4    1             0             0   
6512           5             1     4    1             0             0   

      hours-per-week  native-country  y_test income  RForest  NBGaus  KNeigh  \
0                 39              39              1        0       0       0   
1                 39              39              0        0       0       0   
2                 39              39              0        0       0       0   
3                 39              39              0        0       0       0   
4                 39              39              0        0       0       0   
...              ...             ...            ...      ...     ...     ...   
6508              39              39              0        0       0       0   
6509              39              39              1        1       1       0   
6510              39              39              1        1       1       1   
6511              19              39              0        0       0       0   
6512              39              39              0        0       0       0   

      DecisionT  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
6508          0  
6509          1  
6510          1  
6511          0  
6512          0  

[6513 rows x 19 columns]

# **Evaluation for Classifiers**

In [158]:
#Import relevant metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [159]:
#RANDOM FOREST
acRF=accuracy_score(y_test,clf_pred)
fscoreRF=f1_score(y_test,clf_pred)
conmatrixRF = confusion_matrix(y_test,clf_pred)

#NAIVE BAYES
acNB=accuracy_score(y_test,NB_pred)
fscoreNB = f1_score(y_test,NB_pred)
conmatrixNB = confusion_matrix(y_test,NB_pred)

#K NEIGHBOURS
acKNN=accuracy_score(y_test,KNN_pred)
fscoreKNN=f1_score(y_test,KNN_pred)
conmatrixKNN = confusion_matrix(y_test,KNN_pred)

#DECISION TREE
acDTree = accuracy_score(y_test,model_pred)
fscoreDTree = f1_score(y_test,model_pred)
conmatrixDTree = confusion_matrix(y_test,model_pred)


In [160]:
df = pd.DataFrame(
    {
        "KNeigh": [acKNN, fscoreKNN, conmatrixKNN],
        "Naive Bayes": [acNB, fscoreNB, conmatrixNB],
        "Random Forest": [acRF, fscoreRF, conmatrixRF],
        "Decision Tree": [acDTree, fscoreDTree, conmatrixDTree]
    },
    columns=["KNeigh", "Naive Bayes", "Random Forest", "Decision Tree"],
    index = ["Accuracy", "Fscore", "Confusion Matrix"])
df



KNeigh                Naive Bayes  \
Accuracy                            0.783203                   0.814678   
Fscore                              0.429264                    0.53984   
Confusion Matrix  [[4570, 358], [1054, 531]]  [[4598, 330], [877, 708]]   

                              Random Forest               Decision Tree  
Accuracy                           0.853984                    0.808076  
Fscore                              0.67598                    0.616564  
Confusion Matrix  [[4570, 358], [593, 992]]  [[4258, 670], [580, 1005]]