# **Reading files and shuffling data in the files**

## Reading Files

In [127]:
import pandas as pd
import numpy as np

In [128]:
#Read in txt file of training and testing record
train_df_occ = pd.read_csv("train_df_occ.csv")
test_df_occ = pd.read_csv("test_df_occ.csv")

test_df = pd.read_csv("test_df.csv")

#View briefly train dataset
train_df_occ.head()

FileNotFoundError: [Errno 2] No such file or directory: 'train_df_occ.csv'

In [ ]:
test_df_occ.head()

Temperature  Humidity       Light          CO2  HumidityRatio  Occupancy
0       20.718    25.100    0.000000   512.400000       0.003790          0
1       21.000    23.290    0.000000   509.333333       0.003577          0
2       21.600    28.390    0.000000   895.000000       0.004530          0
3       23.000    26.200  651.666667  1006.166667       0.004553          1
4       22.390    24.912  418.600000   782.800000       0.004169          1

In [ ]:
train_df_occ.info()
train_df_occ.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8143 entries, 0 to 8142
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Temperature    8143 non-null   float64
 1   Humidity       8143 non-null   float64
 2   Light          8143 non-null   float64
 3   CO2            8143 non-null   float64
 4   HumidityRatio  8143 non-null   float64
 5   Occupancy      8143 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 381.8 KB


Temperature     Humidity        Light          CO2  HumidityRatio  \
count  8143.000000  8143.000000  8143.000000  8143.000000    8143.000000   
mean     20.619084    25.731507   119.519375   606.546243       0.003863   
std       1.016916     5.531211   194.755805   314.320877       0.000852   
min      19.000000    16.745000     0.000000   412.750000       0.002674   
25%      19.700000    20.200000     0.000000   439.000000       0.003078   
50%      20.390000    26.222500     0.000000   453.500000       0.003801   
75%      21.390000    30.533333   256.375000   638.833333       0.004352   
max      23.180000    39.117500  1546.333333  2028.500000       0.006476   

         Occupancy  
count  8143.000000  
mean      0.212330  
std       0.408982  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

## Preparing Train and Test datasets

### train_df_occ = train dataset with occupancy
### train_df = train dataset WITHOUT occupancy

### test_df_occ = test dataset with occupancy
### test_df = test WITHOUT occupancy

In [129]:
y_test = test_df_occ['Occupancy']
y_test.head()

0    0
1    0
2    0
3    1
4    1
Name: Occupancy, dtype: int64

In [ ]:
# Extract label class occupancy from training set
occlabel_df = train_df_occ['Occupancy'] #y_train
occlabel_df.head()

0    0
1    0
2    0
3    1
4    1
Name: Occupancy, dtype: int64

In [ ]:
# Remove label class from training set
train_df = train_df_occ.drop(columns=['Occupancy'])
train_df.head()

Temperature   Humidity  Light          CO2  HumidityRatio
0        19.39  25.890000    0.0   471.000000       0.003599
1        20.50  33.500000    0.0   645.000000       0.005000
2        20.20  19.100000    0.0   447.000000       0.002789
3        21.29  33.145000  464.0  1421.750000       0.005195
4        20.50  31.163333  441.0   970.333333       0.004649

In [ ]:
test_df.head()

Temperature  Humidity       Light          CO2  HumidityRatio
0       20.718    25.100    0.000000   512.400000       0.003790
1       21.000    23.290    0.000000   509.333333       0.003577
2       21.600    28.390    0.000000   895.000000       0.004530
3       23.000    26.200  651.666667  1006.166667       0.004553
4       22.390    24.912  418.600000   782.800000       0.004169

In [ ]:
test_df

Temperature   Humidity       Light          CO2  HumidityRatio
0       20.718000  25.100000    0.000000   512.400000       0.003790
1       21.000000  23.290000    0.000000   509.333333       0.003577
2       21.600000  28.390000    0.000000   895.000000       0.004530
3       23.000000  26.200000  651.666667  1006.166667       0.004553
4       22.390000  24.912000  418.600000   782.800000       0.004169
...           ...        ...         ...          ...            ...
2660    20.790000  25.000000    0.000000   529.750000       0.003792
2661    21.600000  28.390000    0.000000   891.666667       0.004530
2662    22.066667  24.666667    0.000000   718.333333       0.004047
2663    20.890000  25.272000  433.000000   649.800000       0.003857
2664    21.236000  26.412000  442.000000   864.400000       0.004119

[2665 rows x 5 columns]

In [ ]:
# Transfer type of ddtaframe to numpy array for training and test sets and label set
X_train = np.array(train_df)
print(X_train[0:5])
X_test = np.array(test_df)
print(X_test[0:5])
y_train = np.array(occlabel_df)
print(y_train[0:5])

[[1.93900000e+01 2.58900000e+01 0.00000000e+00 4.71000000e+02
  3.59944168e-03]
 [2.05000000e+01 3.35000000e+01 0.00000000e+00 6.45000000e+02
  5.00026877e-03]
 [2.02000000e+01 1.91000000e+01 0.00000000e+00 4.47000000e+02
  2.78867884e-03]
 [2.12900000e+01 3.31450000e+01 4.64000000e+02 1.42175000e+03
  5.19526883e-03]
 [2.05000000e+01 3.11633333e+01 4.41000000e+02 9.70333333e+02
  4.64888703e-03]]
[[2.07180000e+01 2.51000000e+01 0.00000000e+00 5.12400000e+02
  3.78983396e-03]
 [2.10000000e+01 2.32900000e+01 0.00000000e+00 5.09333333e+02
  3.57688025e-03]
 [2.16000000e+01 2.83900000e+01 0.00000000e+00 8.95000000e+02
  4.53045755e-03]
 [2.30000000e+01 2.62000000e+01 6.51666667e+02 1.00616667e+03
  4.55297916e-03]
 [2.23900000e+01 2.49120000e+01 4.18600000e+02 7.82800000e+02
  4.16930286e-03]]
[0 0 0 1 1]


# **Random Forest Classification**

### X_train = train dataset WITHOUT occupancy

### X_test = test dataset WITHOUT occupancy
### y_train = 'Occupancy' label from train dataset

In [ ]:
#Random Forest Classification
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(X_train,y_train)


RandomForestClassifier()

In [ ]:
#To predict occupancy using the test's set features
clf_pred=clf.predict(X_test)
print(clf_pred)

[0 0 0 ... 0 1 1]


In [ ]:
# Transfer the array of predicted popularity of test data into dataframe
clf_pred_df = pd.DataFrame(data=clf_pred, columns=['Occupancy'])
clf_pred_df.head(10)

Occupancy
0          0
1          0
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          0

In [ ]:
RFprob_each = clf.predict_proba(X_test)
RFprob_each

array([[0.96, 0.04],
       [0.95, 0.05],
       [0.97, 0.03],
       ...,
       [0.99, 0.01],
       [0.16, 0.84],
       [0.02, 0.98]])

In [ ]:
pos_prob = []
for inner in RFprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.04, 0.05, 0.03, 0.07, 0.58, 0.94, 0.03, 1.0, 0.03, 0.01]

In [ ]:
# Insert result into test_wtpopl, check the prediction correctness
test_df_occ.insert(6, 'RForest', clf_pred_df['Occupancy'])

In [ ]:
test_df_occ.head()

Temperature  Humidity       Light          CO2  HumidityRatio  Occupancy  \
0       20.718    25.100    0.000000   512.400000       0.003790          0   
1       21.000    23.290    0.000000   509.333333       0.003577          0   
2       21.600    28.390    0.000000   895.000000       0.004530          0   
3       23.000    26.200  651.666667  1006.166667       0.004553          1   
4       22.390    24.912  418.600000   782.800000       0.004169          1   

   RForest  
0        0  
1        0  
2        0  
3        0  
4        1

# **Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB

gaus = GaussianNB()
gaus.fit(X_train, y_train)

GaussianNB()

In [ ]:
# To predict popularity using test set's features
NB_pred= gaus.predict(X_test)
print(NB_pred)

[0 0 0 ... 0 1 1]


In [ ]:
# Transfer the array of predicted popularity of test data into dataframe
NB_pred_df = pd.DataFrame(data=NB_pred, columns=['Occupancy'])
NB_pred_df.head(10)

Occupancy
0          0
1          0
2          0
3          1
4          1
5          1
6          0
7          1
8          0
9          0

In [ ]:
NBprob_each = gaus.predict_proba(X_test)
NBprob_each

array([[1.00000000e+00, 7.56127438e-28],
       [1.00000000e+00, 1.50335414e-27],
       [1.00000000e+00, 5.78086413e-25],
       ...,
       [1.00000000e+00, 6.11733779e-26],
       [2.86429338e-04, 9.99713571e-01],
       [3.68655426e-06, 9.99996313e-01]])

In [ ]:
pos_prob = []
for inner in NBprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[7.5612743766558035e-28,
 1.5033541399112353e-27,
 5.780864125403542e-25,
 0.9999999986607833,
 0.9999867676628953,
 0.9999999999997851,
 3.760977597995607e-27,
 0.9999999994984936,
 9.761362252782035e-28,
 1.0947216864358288e-27]

In [ ]:
# Insert result into test_wtpopl, check the prediction correctness
test_df_occ.insert(6, 'NBGaus', NB_pred_df['Occupancy'])

In [ ]:
test_df_occ

Temperature   Humidity       Light          CO2  HumidityRatio  \
0       20.718000  25.100000    0.000000   512.400000       0.003790   
1       21.000000  23.290000    0.000000   509.333333       0.003577   
2       21.600000  28.390000    0.000000   895.000000       0.004530   
3       23.000000  26.200000  651.666667  1006.166667       0.004553   
4       22.390000  24.912000  418.600000   782.800000       0.004169   
...           ...        ...         ...          ...            ...   
2660    20.790000  25.000000    0.000000   529.750000       0.003792   
2661    21.600000  28.390000    0.000000   891.666667       0.004530   
2662    22.066667  24.666667    0.000000   718.333333       0.004047   
2663    20.890000  25.272000  433.000000   649.800000       0.003857   
2664    21.236000  26.412000  442.000000   864.400000       0.004119   

      Occupancy  NBGaus  RForest  
0             0       0        0  
1             0       0        0  
2             0       0        0  
3             1       1        0  
4             1       1        1  
...         ...     ...      ...  
2660          0       0        0  
2661          0       0        0  
2662          0       0        0  
2663          1       1        1  
2664          1       1        1  

[2665 rows x 8 columns]

# **KNN Clasification**


In [ ]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
# To predict popularity using test set's features
KNN_pred= knn.predict(X_test)
print(KNN_pred)

[0 0 0 ... 0 1 1]


In [ ]:
# Transfer the array of predicted popularity of test data into dataframe
KNpredct_df = pd.DataFrame(data=KNN_pred, columns=['Occupancy'])
KNpredct_df.head(10)

Occupancy
0          0
1          0
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          0

In [ ]:
KNprob_each = knn.predict_proba(X_test)
KNprob_each

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [ ]:
pos_prob = []
for inner in KNprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]

[0.0, 0.0, 0.0, 0.42857142857142855, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0]

In [ ]:
# Insert result into test_wtpopl, check the prediction correctness
test_df_occ.insert(len(test_df_occ.columns), 'KNeigh', KNpredct_df['Occupancy'])

In [ ]:
test_df_occ

Temperature   Humidity       Light          CO2  HumidityRatio  \
0       20.718000  25.100000    0.000000   512.400000       0.003790   
1       21.000000  23.290000    0.000000   509.333333       0.003577   
2       21.600000  28.390000    0.000000   895.000000       0.004530   
3       23.000000  26.200000  651.666667  1006.166667       0.004553   
4       22.390000  24.912000  418.600000   782.800000       0.004169   
...           ...        ...         ...          ...            ...   
2660    20.790000  25.000000    0.000000   529.750000       0.003792   
2661    21.600000  28.390000    0.000000   891.666667       0.004530   
2662    22.066667  24.666667    0.000000   718.333333       0.004047   
2663    20.890000  25.272000  433.000000   649.800000       0.003857   
2664    21.236000  26.412000  442.000000   864.400000       0.004119   

      Occupancy  NBGaus  RForest  KNeigh  
0             0       0        0       0  
1             0       0        0       0  
2             0       0        0       0  
3             1       1        0       0  
4             1       1        1       1  
...         ...     ...      ...     ...  
2660          0       0        0       0  
2661          0       0        0       0  
2662          0       0        0       0  
2663          1       1        1       1  
2664          1       1        1       1  

[2665 rows x 9 columns]

# **Evaluation of Accuracy Score for Classifiers**

In [130]:
from sklearn.metrics import accuracy_score

ac=accuracy_score(y_test,KNN_pred)
#y_true = test_df_occ['Occupancy']
#y_true.head()
print(ac)

0.9609756097560975
