# **DATA PREPROCESSING**

In [83]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [84]:
data=pd.read_csv('fertility_Diagnosis.txt')
data

Season  Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  \
0    -0.33        0.69                 0          1                     1   
1    -0.33        0.94                 1          0                     1   
2    -0.33        0.50                 1          0                     0   
3    -0.33        0.75                 0          1                     1   
4    -0.33        0.67                 1          1                     0   
..     ...         ...               ...        ...                   ...   
95   -1.00        0.67                 1          0                     0   
96   -1.00        0.61                 1          0                     0   
97   -1.00        0.67                 1          1                     1   
98   -1.00        0.64                 1          0                     1   
99   -1.00        0.69                 0          1                     1   

    HighFevers  FreqAlcohol  Smoking  HoursSit Output  
0            0          0.8        0      0.88      N  
1            0          0.8        1      0.31      O  
2            0          1.0       -1      0.50      N  
3            0          1.0       -1      0.38      N  
4            0          0.8       -1      0.50      O  
..         ...          ...      ...       ...    ...  
95           0          1.0       -1      0.50      N  
96           0          0.8        0      0.50      N  
97           0          1.0       -1      0.31      N  
98           0          1.0        0      0.19      N  
99           0          0.6       -1      0.19      N  

[100 rows x 10 columns]

In [85]:
data.columns

Index(['Season', 'Age(18-36)', 'ChildishDiseases', 'Accidents',
       'SurgicalIntervention', 'HighFevers', 'FreqAlcohol', 'Smoking',
       'HoursSit', 'Output'],
      dtype='object')

In [86]:
data.drop(columns='Season',axis=1,inplace=True)
data.head()

Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0        0.69                 0          1                     1           0   
1        0.94                 1          0                     1           0   
2        0.50                 1          0                     0           0   
3        0.75                 0          1                     1           0   
4        0.67                 1          1                     0           0   

   FreqAlcohol  Smoking  HoursSit Output  
0          0.8        0      0.88      N  
1          0.8        1      0.31      O  
2          1.0       -1      0.50      N  
3          1.0       -1      0.38      N  
4          0.8       -1      0.50      O

In [87]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Age(18-36)            100 non-null    float64
 1   ChildishDiseases      100 non-null    int64  
 2   Accidents             100 non-null    int64  
 3   SurgicalIntervention  100 non-null    int64  
 4   HighFevers            100 non-null    int64  
 5   FreqAlcohol           100 non-null    float64
 6   Smoking               100 non-null    int64  
 7   HoursSit              100 non-null    float64
 8   Output                100 non-null    object 
dtypes: float64(3), int64(5), object(1)
memory usage: 7.2+ KB


In [88]:
from sklearn.preprocessing import LabelEncoder
data['Output_enc']=LabelEncoder().fit_transform(data[['Output']])
data

C:\Users\vivien\Anaconda3\envs\myenv\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.69                 0          1                     1           0   
1         0.94                 1          0                     1           0   
2         0.50                 1          0                     0           0   
3         0.75                 0          1                     1           0   
4         0.67                 1          1                     0           0   
..         ...               ...        ...                   ...         ...   
95        0.67                 1          0                     0           0   
96        0.61                 1          0                     0           0   
97        0.67                 1          1                     1           0   
98        0.64                 1          0                     1           0   
99        0.69                 0          1                     1           0   

    FreqAlcohol  Smoking  HoursSit Output  Output_enc  
0           0.8        0      0.88      N           0  
1           0.8        1      0.31      O           1  
2           1.0       -1      0.50      N           0  
3           1.0       -1      0.38      N           0  
4           0.8       -1      0.50      O           1  
..          ...      ...       ...    ...         ...  
95          1.0       -1      0.50      N           0  
96          0.8        0      0.50      N           0  
97          1.0       -1      0.31      N           0  
98          1.0        0      0.19      N           0  
99          0.6       -1      0.19      N           0  

[100 rows x 10 columns]

In [89]:
data.drop(columns='Output',axis=1,inplace=True)
data

Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.69                 0          1                     1           0   
1         0.94                 1          0                     1           0   
2         0.50                 1          0                     0           0   
3         0.75                 0          1                     1           0   
4         0.67                 1          1                     0           0   
..         ...               ...        ...                   ...         ...   
95        0.67                 1          0                     0           0   
96        0.61                 1          0                     0           0   
97        0.67                 1          1                     1           0   
98        0.64                 1          0                     1           0   
99        0.69                 0          1                     1           0   

    FreqAlcohol  Smoking  HoursSit  Output_enc  
0           0.8        0      0.88           0  
1           0.8        1      0.31           1  
2           1.0       -1      0.50           0  
3           1.0       -1      0.38           0  
4           0.8       -1      0.50           1  
..          ...      ...       ...         ...  
95          1.0       -1      0.50           0  
96          0.8        0      0.50           0  
97          1.0       -1      0.31           0  
98          1.0        0      0.19           0  
99          0.6       -1      0.19           0  

[100 rows x 9 columns]

In [90]:
data.dtypes

Age(18-36)              float64
ChildishDiseases          int64
Accidents                 int64
SurgicalIntervention      int64
HighFevers                int64
FreqAlcohol             float64
Smoking                   int64
HoursSit                float64
Output_enc                int32
dtype: object

## Prepare train and test dataset

In [91]:
#creating our X feature variables and y outcome variable
X = data.drop('Output_enc',axis=1)
y = data['Output_enc']

In [92]:
#splitting our data into training and testing data set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

# **Random Forest Classification**

In [93]:
#Random Forest Classification
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()
clf.fit(X_train,y_train)


RandomForestClassifier()

In [94]:
#To predict occupancy using the test's set features
clf_pred=clf.predict(X_test)
print(clf_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]


In [95]:
# Transfer the array of predicted popularity of test data into dataframe
clf_pred_df = pd.DataFrame(data=clf_pred, columns=['Output_enc'])
clf_pred_df.head(10)

Output_enc
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0

In [96]:
RFprob_each = clf.predict_proba(X_test)
RFprob_each

array([[1.    , 0.    ],
       [1.    , 0.    ],
       [0.9075, 0.0925],
       [1.    , 0.    ],
       [0.96  , 0.04  ],
       [0.77  , 0.23  ],
       [0.98  , 0.02  ],
       [0.92  , 0.08  ],
       [1.    , 0.    ],
       [0.86  , 0.14  ],
       [0.83  , 0.17  ],
       [0.63  , 0.37  ],
       [0.64  , 0.36  ],
       [0.81  , 0.19  ],
       [0.609 , 0.391 ],
       [0.79  , 0.21  ],
       [0.95  , 0.05  ],
       [0.3   , 0.7   ],
       [0.87  , 0.13  ],
       [0.61  , 0.39  ]])

In [97]:
pos_prob = []
for inner in RFprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.0, 0.0, 0.0925, 0.0, 0.04, 0.23, 0.02, 0.08, 0.0, 0.14]

In [98]:
X_testdf = X_test.copy()
X_testdf.insert(len(X_testdf.columns),'y_test output_enc',y_test)
X_testdf=X_testdf.reset_index(drop=True)
X_testdf

Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.86                 1          1                     1           1   
1         0.61                 1          0                     1           0   
2         0.53                 1          1                     0           0   
3         0.56                 1          0                     1           0   
4         0.64                 1          0                     1           0   
5         0.69                 1          0                     1          -1   
6         0.50                 1          0                     0           0   
7         0.78                 1          1                     0           1   
8         0.58                 0          0                     1           0   
9         0.81                 1          0                     0           0   
10        0.69                 0          1                     1           0   
11        0.75                 1          1                     0           0   
12        0.75                 1          0                     1           1   
13        0.94                 1          1                     1           0   
14        0.69                 0          1                     1           0   
15        0.75                 1          0                     0           0   
16        0.75                 0          1                     1           0   
17        0.67                 0          0                     1           0   
18        0.64                 1          0                     0           1   
19        1.00                 1          0                     1           1   

    FreqAlcohol  Smoking  HoursSit  y_test output_enc  
0           1.0       -1      0.25                  0  
1           1.0       -1      0.63                  0  
2           0.8        0      0.75                  0  
3           1.0       -1      0.63                  0  
4           1.0       -1      0.38                  0  
5           1.0       -1      0.44                  1  
6           1.0       -1      0.50                  0  
7           0.6       -1      0.38                  1  
8           1.0       -1      0.19                  0  
9           1.0       -1      0.38                  0  
10          0.6       -1      0.19                  0  
11          0.8       -1      0.38                  0  
12          0.6        0      0.56                  0  
13          0.2       -1      0.25                  0  
14          0.8        0      0.88                  0  
15          0.6        0      0.25                  0  
16          1.0       -1      0.38                  0  
17          0.6        0      0.50                  1  
18          1.0        1      0.25                  0  
19          0.6        0      0.25                  0

In [99]:
# Insert result, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'RForest', clf_pred_df['Output_enc'])
X_testdf

Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.86                 1          1                     1           1   
1         0.61                 1          0                     1           0   
2         0.53                 1          1                     0           0   
3         0.56                 1          0                     1           0   
4         0.64                 1          0                     1           0   
5         0.69                 1          0                     1          -1   
6         0.50                 1          0                     0           0   
7         0.78                 1          1                     0           1   
8         0.58                 0          0                     1           0   
9         0.81                 1          0                     0           0   
10        0.69                 0          1                     1           0   
11        0.75                 1          1                     0           0   
12        0.75                 1          0                     1           1   
13        0.94                 1          1                     1           0   
14        0.69                 0          1                     1           0   
15        0.75                 1          0                     0           0   
16        0.75                 0          1                     1           0   
17        0.67                 0          0                     1           0   
18        0.64                 1          0                     0           1   
19        1.00                 1          0                     1           1   

    FreqAlcohol  Smoking  HoursSit  y_test output_enc  RForest  
0           1.0       -1      0.25                  0        0  
1           1.0       -1      0.63                  0        0  
2           0.8        0      0.75                  0        0  
3           1.0       -1      0.63                  0        0  
4           1.0       -1      0.38                  0        0  
5           1.0       -1      0.44                  1        0  
6           1.0       -1      0.50                  0        0  
7           0.6       -1      0.38                  1        0  
8           1.0       -1      0.19                  0        0  
9           1.0       -1      0.38                  0        0  
10          0.6       -1      0.19                  0        0  
11          0.8       -1      0.38                  0        0  
12          0.6        0      0.56                  0        0  
13          0.2       -1      0.25                  0        0  
14          0.8        0      0.88                  0        0  
15          0.6        0      0.25                  0        0  
16          1.0       -1      0.38                  0        0  
17          0.6        0      0.50                  1        1  
18          1.0        1      0.25                  0        0  
19          0.6        0      0.25                  0        0

# **Naive Bayes**

In [100]:
from sklearn.naive_bayes import GaussianNB

gaus = GaussianNB()
gaus.fit(X_train, y_train)

GaussianNB()

In [101]:
# To predict popularity using test set's features
NB_pred= gaus.predict(X_test)
print(NB_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [102]:
# Transfer the array of predicted popularity of test data into dataframe
NB_pred_df = pd.DataFrame(data=NB_pred, columns=['Output_enc'])
NB_pred_df.head(10)

Output_enc
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0

In [103]:
NBprob_each = gaus.predict_proba(X_test)
NBprob_each

array([[0.99261429, 0.00738571],
       [0.93180864, 0.06819136],
       [0.95016127, 0.04983873],
       [0.94547435, 0.05452565],
       [0.9388618 , 0.0611382 ],
       [0.94298849, 0.05701151],
       [0.97641328, 0.02358672],
       [0.9832158 , 0.0167842 ],
       [0.90809982, 0.09190018],
       [0.92310288, 0.07689712],
       [0.86414268, 0.13585732],
       [0.9413434 , 0.0586566 ],
       [0.87159704, 0.12840296],
       [0.99677578, 0.00322422],
       [0.69633049, 0.30366951],
       [0.7097247 , 0.2902753 ],
       [0.96270635, 0.03729365],
       [0.5620379 , 0.4379621 ],
       [0.97992617, 0.02007383],
       [0.80110919, 0.19889081]])

In [104]:
pos_prob = []
for inner in NBprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.007385709693619117,
 0.06819135681934535,
 0.04983873173076154,
 0.05452565093034466,
 0.06113820094142147,
 0.05701150650993844,
 0.023586717547630177,
 0.016784197723204244,
 0.09190017650494031,
 0.07689711601419774]

In [105]:
# Insert result, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'NBGaus', NB_pred_df['Output_enc'])
X_testdf

Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.86                 1          1                     1           1   
1         0.61                 1          0                     1           0   
2         0.53                 1          1                     0           0   
3         0.56                 1          0                     1           0   
4         0.64                 1          0                     1           0   
5         0.69                 1          0                     1          -1   
6         0.50                 1          0                     0           0   
7         0.78                 1          1                     0           1   
8         0.58                 0          0                     1           0   
9         0.81                 1          0                     0           0   
10        0.69                 0          1                     1           0   
11        0.75                 1          1                     0           0   
12        0.75                 1          0                     1           1   
13        0.94                 1          1                     1           0   
14        0.69                 0          1                     1           0   
15        0.75                 1          0                     0           0   
16        0.75                 0          1                     1           0   
17        0.67                 0          0                     1           0   
18        0.64                 1          0                     0           1   
19        1.00                 1          0                     1           1   

    FreqAlcohol  Smoking  HoursSit  y_test output_enc  RForest  NBGaus  
0           1.0       -1      0.25                  0        0       0  
1           1.0       -1      0.63                  0        0       0  
2           0.8        0      0.75                  0        0       0  
3           1.0       -1      0.63                  0        0       0  
4           1.0       -1      0.38                  0        0       0  
5           1.0       -1      0.44                  1        0       0  
6           1.0       -1      0.50                  0        0       0  
7           0.6       -1      0.38                  1        0       0  
8           1.0       -1      0.19                  0        0       0  
9           1.0       -1      0.38                  0        0       0  
10          0.6       -1      0.19                  0        0       0  
11          0.8       -1      0.38                  0        0       0  
12          0.6        0      0.56                  0        0       0  
13          0.2       -1      0.25                  0        0       0  
14          0.8        0      0.88                  0        0       0  
15          0.6        0      0.25                  0        0       0  
16          1.0       -1      0.38                  0        0       0  
17          0.6        0      0.50                  1        1       0  
18          1.0        1      0.25                  0        0       0  
19          0.6        0      0.25                  0        0       0

# **KNN Classification**

In [106]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [107]:
# To predict popularity using test set's features
KNN_pred= knn.predict(X_test)
print(KNN_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [108]:
# Transfer the array of predicted popularity of test data into dataframe
KNpredct_df = pd.DataFrame(data=KNN_pred, columns=['Output_enc'])
KNpredct_df.head(10)

Output_enc
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0

In [109]:
KNprob_each = knn.predict_proba(X_test)
KNprob_each

array([[1.        , 0.        ],
       [0.57142857, 0.42857143],
       [0.71428571, 0.28571429],
       [0.57142857, 0.42857143],
       [0.57142857, 0.42857143],
       [0.71428571, 0.28571429],
       [1.        , 0.        ],
       [0.85714286, 0.14285714],
       [0.71428571, 0.28571429],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.85714286, 0.14285714],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.85714286, 0.14285714],
       [0.85714286, 0.14285714],
       [1.        , 0.        ],
       [0.71428571, 0.28571429],
       [0.71428571, 0.28571429],
       [1.        , 0.        ]])

In [110]:
pos_prob = []
for inner in KNprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]

[0.0,
 0.42857142857142855,
 0.2857142857142857,
 0.42857142857142855,
 0.42857142857142855,
 0.2857142857142857,
 0.0,
 0.14285714285714285,
 0.2857142857142857,
 0.0]

In [111]:
# Insert result, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'KNeigh', KNpredct_df['Output_enc'])
X_testdf


Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.86                 1          1                     1           1   
1         0.61                 1          0                     1           0   
2         0.53                 1          1                     0           0   
3         0.56                 1          0                     1           0   
4         0.64                 1          0                     1           0   
5         0.69                 1          0                     1          -1   
6         0.50                 1          0                     0           0   
7         0.78                 1          1                     0           1   
8         0.58                 0          0                     1           0   
9         0.81                 1          0                     0           0   
10        0.69                 0          1                     1           0   
11        0.75                 1          1                     0           0   
12        0.75                 1          0                     1           1   
13        0.94                 1          1                     1           0   
14        0.69                 0          1                     1           0   
15        0.75                 1          0                     0           0   
16        0.75                 0          1                     1           0   
17        0.67                 0          0                     1           0   
18        0.64                 1          0                     0           1   
19        1.00                 1          0                     1           1   

    FreqAlcohol  Smoking  HoursSit  y_test output_enc  RForest  NBGaus  KNeigh  
0           1.0       -1      0.25                  0        0       0       0  
1           1.0       -1      0.63                  0        0       0       0  
2           0.8        0      0.75                  0        0       0       0  
3           1.0       -1      0.63                  0        0       0       0  
4           1.0       -1      0.38                  0        0       0       0  
5           1.0       -1      0.44                  1        0       0       0  
6           1.0       -1      0.50                  0        0       0       0  
7           0.6       -1      0.38                  1        0       0       0  
8           1.0       -1      0.19                  0        0       0       0  
9           1.0       -1      0.38                  0        0       0       0  
10          0.6       -1      0.19                  0        0       0       0  
11          0.8       -1      0.38                  0        0       0       0  
12          0.6        0      0.56                  0        0       0       0  
13          0.2       -1      0.25                  0        0       0       0  
14          0.8        0      0.88                  0        0       0       0  
15          0.6        0      0.25                  0        0       0       0  
16          1.0       -1      0.38                  0        0       0       0  
17          0.6        0      0.50                  1        1       0       0  
18          1.0        1      0.25                  0        0       0       0  
19          0.6        0      0.25                  0        0       0       0

# **Decision Tree**

In [112]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [113]:
#To predict occupancy using the test's set features
model_pred=model.predict(X_test)
print(model_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1]


In [114]:
# Transfer the array of predicted popularity of test data into dataframe
model_pred_df = pd.DataFrame(data=model_pred, columns=['Output_enc'])
model_pred_df.head(10)

Output_enc
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0

In [115]:
DTprob_each = model.predict_proba(X_test)
DTprob_each

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [116]:
pos_prob = []
for inner in DTprob_each:
    pos_prob.append(inner[1])
pos_prob[0:10]


[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [117]:
# Insert result, check the prediction correctness
X_testdf.insert(len(X_testdf.columns), 'DecisionT', model_pred_df['Output_enc'])
X_testdf

Age(18-36)  ChildishDiseases  Accidents  SurgicalIntervention  HighFevers  \
0         0.86                 1          1                     1           1   
1         0.61                 1          0                     1           0   
2         0.53                 1          1                     0           0   
3         0.56                 1          0                     1           0   
4         0.64                 1          0                     1           0   
5         0.69                 1          0                     1          -1   
6         0.50                 1          0                     0           0   
7         0.78                 1          1                     0           1   
8         0.58                 0          0                     1           0   
9         0.81                 1          0                     0           0   
10        0.69                 0          1                     1           0   
11        0.75                 1          1                     0           0   
12        0.75                 1          0                     1           1   
13        0.94                 1          1                     1           0   
14        0.69                 0          1                     1           0   
15        0.75                 1          0                     0           0   
16        0.75                 0          1                     1           0   
17        0.67                 0          0                     1           0   
18        0.64                 1          0                     0           1   
19        1.00                 1          0                     1           1   

    FreqAlcohol  Smoking  HoursSit  y_test output_enc  RForest  NBGaus  \
0           1.0       -1      0.25                  0        0       0   
1           1.0       -1      0.63                  0        0       0   
2           0.8        0      0.75                  0        0       0   
3           1.0       -1      0.63                  0        0       0   
4           1.0       -1      0.38                  0        0       0   
5           1.0       -1      0.44                  1        0       0   
6           1.0       -1      0.50                  0        0       0   
7           0.6       -1      0.38                  1        0       0   
8           1.0       -1      0.19                  0        0       0   
9           1.0       -1      0.38                  0        0       0   
10          0.6       -1      0.19                  0        0       0   
11          0.8       -1      0.38                  0        0       0   
12          0.6        0      0.56                  0        0       0   
13          0.2       -1      0.25                  0        0       0   
14          0.8        0      0.88                  0        0       0   
15          0.6        0      0.25                  0        0       0   
16          1.0       -1      0.38                  0        0       0   
17          0.6        0      0.50                  1        1       0   
18          1.0        1      0.25                  0        0       0   
19          0.6        0      0.25                  0        0       0   

    KNeigh  DecisionT  
0        0          0  
1        0          0  
2        0          0  
3        0          0  
4        0          0  
5        0          0  
6        0          0  
7        0          0  
8        0          0  
9        0          0  
10       0          0  
11       0          0  
12       0          1  
13       0          0  
14       0          0  
15       0          1  
16       0          0  
17       0          1  
18       0          0  
19       0          1

# **Evaluation of Classifiers**

In [118]:
#Import relevant metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [119]:
#RANDOM FOREST
acRF=accuracy_score(y_test,clf_pred)
fscoreRF=f1_score(y_test,clf_pred)
conmatrixRF = confusion_matrix(y_test,clf_pred)

#NAIVE BAYES
acNB=accuracy_score(y_test,NB_pred)
fscoreNB = f1_score(y_test,NB_pred)
conmatrixNB = confusion_matrix(y_test,NB_pred)

#K NEIGHBOURS
acKNN=accuracy_score(y_test,KNN_pred)
fscoreKNN=f1_score(y_test,KNN_pred)
conmatrixKNN = confusion_matrix(y_test,KNN_pred)

#DECISION TREE
acDTree = accuracy_score(y_test,model_pred)
fscoreDTree = f1_score(y_test,model_pred)
conmatrixDTree = confusion_matrix(y_test,model_pred)


In [120]:
df = pd.DataFrame(
    {
        "KNeigh": [acKNN, fscoreKNN, conmatrixKNN],
        "Naive Bayes": [acNB, fscoreNB, conmatrixNB],
        "Random Forest": [acRF, fscoreRF, conmatrixRF],
        "Decision Tree": [acDTree, fscoreDTree, conmatrixDTree]
    },
    columns=["KNeigh", "Naive Bayes", "Random Forest", "Decision Tree"],
    index = ["Accuracy", "Fscore", "Confusion Matrix"])
df



KNeigh        Naive Bayes      Random Forest  \
Accuracy                       0.85               0.85                0.9   
Fscore                          0.0                0.0                0.5   
Confusion Matrix  [[17, 0], [3, 0]]  [[17, 0], [3, 0]]  [[17, 0], [2, 1]]   

                      Decision Tree  
Accuracy                       0.75  
Fscore                     0.285714  
Confusion Matrix  [[14, 3], [2, 1]]